blank_issues_enabled: true
contact_links:
  - name: Server issue?
    url: https://github.com/TeamBrot/server/issues
    about: if you encounter issues with the development server open your issue here.
